Creat models for my database
ruxmur/bootcamp-project-laravel pull request #2
Opened 2021-12-13 14:00 UTC by ruxmur

2021-12-13 14:03 UTC, vistrati requested changes

2021-12-13 14:03 UTC, vistrati commented on app/Models/about_client.php
> +class about_client extends Model
please name in in camelCase `AboutCLient`

2021-12-13 14:03 UTC, vistrati commented on app/Models/client.php
> +    public function about_client()
`aboutCLlient`

2021-12-14 08:39 UTC, vistrati requested changes

2021-12-14 08:39 UTC, vistrati commented on app/Models/client.php
> +    public function membership()
`memberships`, if has many

2021-12-14 08:39 UTC, vistrati commented on app/Models/client.php
> +    public function reservation()
`reservations`

2021-12-20 09:04 UTC, vistrati requested changes

2021-12-20 09:04 UTC, vistrati commented on app/Models/reservation.php
> +        return $this->belongsToMany('client');
PLease pay more attention to relations
https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-inverse

2021-12-20 09:04 UTC, vistrati commented on app/Models/reservation.php
> +        return $this->belongsToMany('workoutType');
Please pay more attention to relation types
https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-inverse

2021-12-20 09:04 UTC, vistrati commented on app/Models/workout_type.php
> +        return $this->belongsTo('reservation');
please pay more attention to relation.
https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-inverse

2021-12-20 09:04 UTC, vistrati commented on app/Models/workout_type.php
> +        return $this->belongsToMany('coach');
If you use different table names for pivot table then you should specify the name
https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-model-structure

![Screenshot (53)](https://user-images.githubusercontent.com/79978517/146738611-4510f176-9667-4170-825f-81fa17c3ba34.png)

2021-12-20 09:04 UTC, vistrati commented on app/Models/workout_type.php
> +        return $this->belongsToMany('client');
If you use different table names for pivot table then you should specify the name
https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-model-structure

![Screenshot (53)](https://user-images.githubusercontent.com/79978517/146738611-4510f176-9667-4170-825f-81fa17c3ba34.png)

2021-12-22 21:20 UTC, ruxmur commented on app/Models/reservation.php
> +    public function workout_types()
all mistakes have been corrected. thank you

2022-01-16 15:06 UTC, merged